"""baseline (empty)

Establishes the migration chain head with no schema. Models land in later
phases via autogenerated revisions stacked on top of this one.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-06-16
"""

from __future__ import annotations

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "0001_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """No-op baseline."""
    pass


def downgrade() -> None:
    """No-op baseline."""
    pass
