"""create avatar domain

Revision ID: 319818f0f329
Revises: ee9743d0bfe0
Create Date: 2026-06-16 13:45:55.538054
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "319818f0f329"
down_revision: str | None = "ee9743d0bfe0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "avatars",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "processing", "ready", "failed", name="avatar_status", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("profile_path", sa.String(length=1024), nullable=True),
        sa.Column("thumbnail_path", sa.String(length=1024), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("source_video_id", sa.Integer(), nullable=True),
        sa.Column("voice_model_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["source_video_id"], ["training_videos.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["voice_model_id"], ["voice_models.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("avatars", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_avatars_user_id"), ["user_id"], unique=False)

    op.create_table(
        "training_scripts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("avatar_id", sa.Integer(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["avatar_id"], ["avatars.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("training_scripts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_training_scripts_avatar_id"), ["avatar_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_training_scripts_user_id"), ["user_id"], unique=False)

    op.create_table(
        "training_videos",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("avatar_id", sa.Integer(), nullable=True),
        sa.Column("script_id", sa.Integer(), nullable=True),
        sa.Column("file_path", sa.String(length=1024), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("resolution", sa.String(length=16), nullable=True),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "uploaded",
                "processing",
                "analyzed",
                "failed",
                name="video_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["avatar_id"], ["avatars.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["script_id"], ["training_scripts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("training_videos", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_training_videos_avatar_id"), ["avatar_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_training_videos_script_id"), ["script_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_training_videos_user_id"), ["user_id"], unique=False)

    op.create_table(
        "voice_models",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("avatar_id", sa.Integer(), nullable=False),
        sa.Column("model_path", sa.String(length=1024), nullable=True),
        sa.Column("reference_audio_path", sa.String(length=1024), nullable=True),
        sa.Column("sample_rate", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "training", "ready", "failed", name="voice_status", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["avatar_id"], ["avatars.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("avatar_id", name="uq_voice_models_avatar_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("voice_models")
    with op.batch_alter_table("training_videos", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_training_videos_user_id"))
        batch_op.drop_index(batch_op.f("ix_training_videos_script_id"))
        batch_op.drop_index(batch_op.f("ix_training_videos_avatar_id"))

    op.drop_table("training_videos")
    with op.batch_alter_table("training_scripts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_training_scripts_user_id"))
        batch_op.drop_index(batch_op.f("ix_training_scripts_avatar_id"))

    op.drop_table("training_scripts")
    with op.batch_alter_table("avatars", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_avatars_user_id"))

    op.drop_table("avatars")
    # ### end Alembic commands ###
