"""create generation tables

Revision ID: fa6a5a1b2c9f
Revises: 319818f0f329
Create Date: 2026-06-16 14:05:07.777346
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa6a5a1b2c9f"
down_revision: str | None = "319818f0f329"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "generated_videos",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("avatar_id", sa.Integer(), nullable=False),
        sa.Column("file_path", sa.String(length=1024), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("resolution", sa.String(length=16), nullable=True),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["avatar_id"], ["avatars.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["job_id"], ["generation_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("generated_videos", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_generated_videos_avatar_id"), ["avatar_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_generated_videos_job_id"), ["job_id"], unique=False)

    op.create_table(
        "generation_jobs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("avatar_id", sa.Integer(), nullable=False),
        sa.Column("script_text", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "processing",
                "completed",
                "failed",
                "cancelled",
                name="job_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("output_video_id", sa.Integer(), nullable=True),
        sa.Column(
            "queued_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["avatar_id"], ["avatars.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["output_video_id"], ["generated_videos.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("generation_jobs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_generation_jobs_avatar_id"), ["avatar_id"], unique=False
        )
        batch_op.create_index(
            "ix_generation_jobs_status_queued_at", ["status", "queued_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_generation_jobs_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("generation_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_generation_jobs_user_id"))
        batch_op.drop_index("ix_generation_jobs_status_queued_at")
        batch_op.drop_index(batch_op.f("ix_generation_jobs_avatar_id"))

    op.drop_table("generation_jobs")
    with op.batch_alter_table("generated_videos", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_generated_videos_job_id"))
        batch_op.drop_index(batch_op.f("ix_generated_videos_avatar_id"))

    op.drop_table("generated_videos")
    # ### end Alembic commands ###
